name: Forge mod incompatibility
description: If Essentials-S is acting strange with a forge mod
title: "[Mod Bug]: "
labels: [ "bug", "triage", "external source" ]
body:
  - type: dropdown
    id: api
    attributes:
      label: API version
      description: "What Sponge API are you using?"
      options:
        - 8.x.x
        - 9.x.x
        - 10.x.x
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge version
      description: "What forge version are you running (be specific)?"
    validations:
      required: true
  - type: input
    id: essentials-s-version
    attributes:
      label: Essentials-S version
      description: "Please state the version of Essentials-S you are using as shown in '/essentials info' command"
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: other-mod
    attributes:
      label: Mod
      description: "Please provide the URL for the affected mod"
      placeholder: "https://ore.spongepowered.com"
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Describe the issue
    validations:
      required: true
  - type: textarea
    id: recreate
    attributes:
      label: Steps-To-Recreate
      description: Describe how to recreate the issue
