name: Plugin incompatibility
description: If Essentials-S is acting strange with another plugin
title: "[Plugin Bug]: "
labels: [ "bug", "triage", "external source" ]
body:
  - type: dropdown
    id: api
    attributes:
      label: API version
      description: "What Sponge API are you using?"
      options:
        - 8.x.x
        - 9.x.x
        - 10.x.x
    validations:
      required: true
  - type: dropdown
    id: implementation
    attributes:
      label: Sponge platform
      description: "What platform of sponge are you running?"
      options:
        - Sponge Forge
        - Sponge Vanilla
        - Lantern
    validations:
      required: true
  - type: input
    id: essentials-s-version
    attributes:
      label: Essentials-S version
      description: "Please state the version of Essentials-S you are using as shown in '/essentials info' command"
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: other-plugin
    attributes:
      label: Plugin
      description: "Please provide the Sponge Ore URL for the affected plugin"
      placeholder: "https://ore.spongepowered.com"
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Describe the issue
    validations:
      required: true
  - type: textarea
    id: recreate
    attributes:
      label: Steps-To-Recreate
      description: Describe how to recreate the issue
